-- db/00_replay_base.sql — REPLAY SCAFFOLD ONLY. NOT A MIGRATION.
--
-- GENERATED by scripts/generate_replay_base.py — DO NOT EDIT BY HAND.
--
-- The db/01..db/101 chain is not self-contained: the core tables were
-- created in the Supabase editor before the chain began, so the chain
-- can only be proven against a fresh schema with this pre-chain base.
-- It is the latest backup's schema MINUS every table the chain itself
-- creates, plus a hand supplement for pre-chain tables dropped
-- mid-chain (people/organizations — db/75) that early migrations
-- reference. Never apply this file to production.
--
-- Derived from backup: rhodey-public-20260808-110504.sql
-- Pre-chain tables: 25 from backup + 8 supplement

CREATE TABLE public.call_pending_items (
    id BIGSERIAL PRIMARY KEY,
    suggested_title TEXT,
    suggested_project TEXT,
    summary TEXT,
    recording_id BIGINT,
    danny_decision TEXT,
    decided_at TIMESTAMPTZ,
    shown_in_brief BOOLEAN,
    possible_duplicate BOOLEAN,
    created_at TIMESTAMPTZ,
    action_type TEXT,
    people_mentioned JSONB
);

CREATE TABLE public.email_drafts (
    id BIGSERIAL PRIMARY KEY,
    email_id BIGINT
);

CREATE TABLE public.email_pending_tasks (
    id BIGSERIAL PRIMARY KEY,
    email_id BIGINT,
    suggested_title TEXT,
    suggested_project TEXT,
    is_human_sender BOOLEAN,
    danny_decision TEXT,
    shown_in_brief BOOLEAN,
    possible_duplicate BOOLEAN,
    duplicate_of_title TEXT,
    project_confidence DOUBLE PRECISION,
    project_mapping_reason TEXT
);

CREATE TABLE public.emails (
    id BIGSERIAL PRIMARY KEY,
    source TEXT,
    direction TEXT,
    message_id TEXT,
    thread_id TEXT,
    sender TEXT,
    sender_email TEXT,
    subject TEXT,
    body_raw TEXT,
    body_summary TEXT,
    classification TEXT,
    linked_person_id BIGINT,
    linked_project_id BIGINT,
    embedding vector(768),
    received_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ,
    gmail_labels JSONB,
    status TEXT
);

CREATE TABLE public.organizations (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    name TEXT UNIQUE,
    graph_node_id UUID
);

CREATE TABLE public.people (
    id BIGSERIAL PRIMARY KEY,
    name TEXT,
    role TEXT,
    strategic_weight DOUBLE PRECISION,
    source TEXT,
    created_at TIMESTAMPTZ,
    graph_node_id UUID
);

CREATE TABLE public.person_aliases (
    id BIGSERIAL PRIMARY KEY,
    alias TEXT,
    canonical_name TEXT,
    resolution_count INTEGER
);

CREATE TABLE public.whatsapp_messages (
    id BIGSERIAL PRIMARY KEY,
    sender_name TEXT,
    sender_phone TEXT,
    message_text TEXT,
    classification TEXT,
    summary TEXT,
    suggested_title TEXT,
    suggested_project TEXT,
    has_memory_value BOOLEAN,
    danny_decision TEXT,
    decided_at TIMESTAMPTZ,
    shown_in_brief BOOLEAN,
    embedding vector(768),
    received_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ,
    linked_person_name TEXT
);

CREATE TABLE public.agent_queue (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    query text,
    status text DEFAULT 'pending'::text,
    priority text DEFAULT 'batch'::text,
    created_at timestamp with time zone DEFAULT now(),
    completed_at timestamp with time zone,
    task text,
    metadata jsonb
);

CREATE TABLE public.app_intelligence (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    voice_line text DEFAULT ''::text NOT NULL,
    pulse_mode text DEFAULT ''::text NOT NULL,
    nag_list jsonb DEFAULT '[]'::jsonb NOT NULL,
    stale_list jsonb DEFAULT '[]'::jsonb NOT NULL,
    overdue_list jsonb DEFAULT '[]'::jsonb NOT NULL,
    vaulted_count integer DEFAULT 0 NOT NULL,
    delta_snapshot jsonb DEFAULT '[]'::jsonb NOT NULL,
    context text DEFAULT ''::text NOT NULL,
    insights jsonb DEFAULT '[]'::jsonb NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    pulse_run_id text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    top_focal_item jsonb,
    transparency_report text,
    context_bar text
);

CREATE TABLE public.audit_logs (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    service text NOT NULL,
    level text NOT NULL,
    message text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.call_recordings (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    drive_file_id text NOT NULL,
    drive_file_name text NOT NULL,
    mime_type text,
    file_size_bytes bigint,
    duration_seconds integer,
    transcript text,
    extraction jsonb,
    status text DEFAULT 'pending'::text NOT NULL,
    metadata jsonb,
    created_at timestamp with time zone DEFAULT now(),
    processed_at timestamp with time zone,
    error_message text
);

CREATE TABLE public.canonical_pages (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    content text,
    category text,
    entity_id uuid,
    embedding public.vector(768),
    updated_at timestamp with time zone DEFAULT now(),
    project_id integer,
    source_count integer DEFAULT 0,
    last_synth_at timestamp with time zone,
    is_sparse boolean DEFAULT false,
    is_archived boolean DEFAULT false,
    archived_at timestamp with time zone,
    archive_reason text,
    is_current boolean DEFAULT true,
    version integer DEFAULT 1,
    supersedes_id bigint,
    organization_id uuid
);

CREATE TABLE public.clarification_feedback (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    shortcode text NOT NULL,
    question_type text NOT NULL,
    question text NOT NULL,
    answer text,
    response_type text,
    source_table text NOT NULL,
    source_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    expires_at timestamp with time zone NOT NULL,
    resolved_at timestamp with time zone,
    sent_at timestamp with time zone
);

CREATE TABLE public.clusters (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    status text DEFAULT 'active'::text,
    created_at timestamp with time zone DEFAULT now(),
    description text
);

CREATE TABLE public.conversations (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    chat_id bigint NOT NULL,
    session_id uuid NOT NULL,
    role text NOT NULL,
    intent text,
    content text NOT NULL,
    token_count integer DEFAULT 0,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.core_config (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    key text NOT NULL,
    content text NOT NULL,
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.dead_letter_queue (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    source_table text DEFAULT 'raw_dumps'::text,
    source_id text,
    content text,
    failure_reason text,
    retry_count integer DEFAULT 0,
    resolved boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.graph_edges (
    id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL PRIMARY KEY,
    source_node_id uuid,
    target_node_id uuid,
    relationship text,
    weight double precision,
    metadata jsonb,
    created_at timestamp with time zone DEFAULT now(),
    valid_from timestamp with time zone DEFAULT now() NOT NULL,
    source_ref text,
    epistemic_status text DEFAULT 'inferred'::text NOT NULL,
    archived boolean DEFAULT false NOT NULL
);

CREATE TABLE public.graph_nodes (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    label text NOT NULL,
    type text,
    metadata jsonb,
    embedding public.vector(768),
    canonical_page_id integer,
    canonical_id uuid,
    created_at timestamp with time zone DEFAULT now(),
    epistemic_status text DEFAULT 'inferred'::text NOT NULL,
    reference_count integer DEFAULT 0 NOT NULL,
    last_referenced_at timestamp with time zone,
    db_record_id text
);

CREATE TABLE public.graph_type_overrides (
    label text NOT NULL,
    node_type text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.memories (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    content text NOT NULL,
    metadata jsonb,
    embedding public.vector(768),
    created_at timestamp with time zone DEFAULT now(),
    memory_type text DEFAULT 'note'::text,
    source text,
    embedding_status text DEFAULT 'success'::text,
    is_archived boolean DEFAULT false,
    archived_at timestamp with time zone,
    archive_reason text,
    importance_score integer DEFAULT 5,
    last_accessed_at timestamp with time zone DEFAULT now(),
    supersedes_id bigint,
    pruned boolean DEFAULT false,
    pruned_at timestamp with time zone,
    pruned_reason text,
    superseded_by bigint,
    is_current boolean DEFAULT true,
    version integer DEFAULT 1,
    project_id bigint,
    sentiment_score real,
    sentiment text,
    entities_mentioned text[],
    organization_id uuid
);

CREATE TABLE public.model_registry (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    model_name text NOT NULL,
    provider text NOT NULL,
    version text,
    input_tokens integer,
    output_tokens integer,
    latency_ms integer,
    success boolean DEFAULT true,
    error_message text,
    created_at timestamp with time zone DEFAULT now(),
    metadata jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE public.pending_enrichment_jobs (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    job_type text NOT NULL,
    target_type text NOT NULL,
    target_id integer NOT NULL,
    content text NOT NULL,
    related_id text,
    status text DEFAULT 'pending'::text NOT NULL,
    retry_count integer DEFAULT 0 NOT NULL,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone
);

CREATE TABLE public.pending_graph_edges (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source_label text NOT NULL,
    target_label text NOT NULL,
    relationship text NOT NULL,
    source_text text,
    confidence real DEFAULT 0.5,
    status text DEFAULT 'pending'::text,
    source_node_id uuid,
    target_node_id uuid,
    created_at timestamp with time zone DEFAULT now(),
    source_table text,
    clarification_status text DEFAULT 'none'::text,
    eval_context jsonb,
    shortcode text,
    evaluated_at timestamp with time zone,
    epistemic_status text DEFAULT 'inferred'::text,
    valid_from timestamp with time zone,
    source_ref text,
    source_type text,
    target_type text
);

CREATE TABLE public.processed_updates (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    update_id bigint NOT NULL,
    chat_id bigint,
    processed_at timestamp with time zone DEFAULT now(),
    request_id text,
    metadata jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE public.projects (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    status text DEFAULT 'active'::text,
    context text NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT now(),
    is_active boolean DEFAULT true,
    parent_project_id integer,
    keywords text[] DEFAULT '{}'::text[],
    is_current boolean DEFAULT true,
    version integer DEFAULT 1,
    supersedes_id bigint
);

CREATE TABLE public.pulse_runs (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    status text DEFAULT 'running'::text NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    failed_at timestamp with time zone,
    error_message text,
    dumps_processed integer,
    tasks_created integer,
    pulse_type text,
    trigger text,
    metadata jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE public.raw_dumps (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    content text NOT NULL,
    source text DEFAULT 'telegram'::text,
    is_processed boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    metadata jsonb,
    status text DEFAULT 'pending'::text,
    embedding public.vector(768),
    request_id text,
    direction text DEFAULT 'incoming'::text,
    sender text DEFAULT 'telegram'::text,
    message_type text DEFAULT 'chat'::text,
    dedup_key text
);

CREATE TABLE public.resources (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    url text NOT NULL,
    title text,
    summary text,
    category text,
    project_id bigint,
    created_at timestamp with time zone DEFAULT now(),
    strategic_note text,
    cluster_id bigint,
    enriched_at timestamp with time zone,
    embedding public.vector(768),
    is_current boolean DEFAULT true,
    version integer DEFAULT 1,
    supersedes_id integer,
    organization_id uuid
);

CREATE TABLE public.system_audit_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    function_name text NOT NULL,
    event_type text,
    message text,
    raw_input text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.tasks (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    status text DEFAULT 'todo'::text,
    priority text DEFAULT 'medium'::text,
    project_id bigint,
    estimated_minutes integer DEFAULT 15,
    is_revenue_critical boolean DEFAULT false,
    deadline date,
    created_at timestamp with time zone DEFAULT now(),
    completed_at timestamp with time zone,
    google_task_id text,
    reminder_at timestamp with time zone,
    google_event_id text,
    duration_mins integer DEFAULT 15,
    source text,
    email_id bigint,
    dedup_key character varying(16),
    updated_at timestamp with time zone DEFAULT now(),
    is_current boolean DEFAULT true,
    version integer DEFAULT 1,
    supersedes_id bigint,
    recurrence text,
    direction text,
    committed_to text,
    committed_on timestamp with time zone
);

ALTER TABLE public.core_config ADD CONSTRAINT core_config_key_key UNIQUE (key);
