-- Migration 52: Create app_intelligence table
--
-- Stores structured pulse intelligence for the Flutter app.
-- Written by the pulse engine (core/pulse/briefing.py) on every pulse run.
-- Read by the API briefing (api/briefing.py) on every app open.
--
-- This table replaces the ad-hoc metadata extraction from raw_dumps
-- with a dedicated, typed schema. The pulse engine writes to this table
-- AFTER generating the Telegram briefing — Telegram path is unchanged.

CREATE TABLE IF NOT EXISTS app_intelligence (
    id BIGSERIAL PRIMARY KEY,
    -- Rhodey's voice line (1-2 sentences, generated by LLM alongside telegram briefing)
    voice_line TEXT NOT NULL DEFAULT '',
    -- Pulse mode: "morning", "afternoon", "closing_loop", "weekend", "pre_monday"
    pulse_mode TEXT NOT NULL DEFAULT '',
    -- Structured lists
    nag_list JSONB NOT NULL DEFAULT '[]'::jsonb,       -- Urgent tasks stale >48h
    stale_list JSONB NOT NULL DEFAULT '[]'::jsonb,      -- Tasks stale >7d
    overdue_list JSONB NOT NULL DEFAULT '[]'::jsonb,    -- Overdue tasks with deadlines
    vaulted_count INTEGER NOT NULL DEFAULT 0,           -- Tasks hidden by horizon filter
    -- Delta snapshot for computing what changed since last app open
    -- Stores task IDs + titles as a JSON snapshot
    delta_snapshot JSONB NOT NULL DEFAULT '[]'::jsonb,
    -- Context bar insight text
    context TEXT NOT NULL DEFAULT '',
    -- Computed insights list
    insights JSONB NOT NULL DEFAULT '[]'::jsonb,
    -- Free-form metadata from the pulse run
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    -- Timing
    pulse_run_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Each pulse run creates a new row; only the latest matters
    CONSTRAINT unique_pulse_run UNIQUE (pulse_run_id)
);

-- Index for fast "get latest" query
CREATE INDEX IF NOT EXISTS idx_app_intelligence_created_at
    ON app_intelligence (created_at DESC);

-- Allow service_role full access
GRANT ALL ON app_intelligence TO service_role;
GRANT USAGE ON SEQUENCE app_intelligence_id_seq TO service_role;
