-- Supabase Database Schema Dump
-- Auto-generated from introspected JSON

-- TABLE: public.core_config
CREATE TABLE public.core_config (
    id int8 GENERATED ALWAYS AS IDENTITY,
    key text,
    content text,
    updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.core_config ADD PRIMARY KEY (id);


-- TABLE: public.projects
CREATE TABLE public.projects (
    id int8 GENERATED ALWAYS AS IDENTITY,
    name text,
    status text DEFAULT 'active'::text,
    context text,
    description text,
    created_at timestamptz DEFAULT now(),
    org_tag text DEFAULT 'INBOX'::text,
    is_active bool DEFAULT true,
    parent_project_id int4,
    keywords _text DEFAULT '{}'::text[],
    is_current bool DEFAULT true,
    version int4 DEFAULT 1,
    supersedes_id int8
);

ALTER TABLE public.projects ADD PRIMARY KEY (id);

ALTER TABLE public ADD CONSTRAINT resources_project_id_fkey FOREIGN KEY (resources) REFERENCES public(projects);
ALTER TABLE public ADD CONSTRAINT tasks_project_id_fkey FOREIGN KEY (tasks) REFERENCES public(projects);
ALTER TABLE public ADD CONSTRAINT email_pending_tasks_suggested_project_id_fkey FOREIGN KEY (email_pending_tasks) REFERENCES public(projects);
ALTER TABLE public ADD CONSTRAINT emails_linked_project_id_fkey FOREIGN KEY (emails) REFERENCES public(projects);
ALTER TABLE public ADD CONSTRAINT projects_parent_project_id_fkey FOREIGN KEY (projects) REFERENCES public(projects);
ALTER TABLE public ADD CONSTRAINT canonical_pages_project_id_fkey FOREIGN KEY (canonical_pages) REFERENCES public(projects);
ALTER TABLE public ADD CONSTRAINT memories_project_id_fkey FOREIGN KEY (memories) REFERENCES public(projects);

-- TABLE: public.tasks
CREATE TABLE public.tasks (
    id int8 GENERATED ALWAYS AS IDENTITY,
    title text,
    status text DEFAULT 'todo'::text,
    priority text DEFAULT 'medium'::text,
    project_id int8,
    estimated_minutes int4 DEFAULT 15,
    is_revenue_critical bool DEFAULT false,
    deadline date,
    created_at timestamptz DEFAULT now(),
    completed_at timestamptz,
    google_task_id text,
    reminder_at timestamptz,
    google_event_id text,
    duration_mins int4 DEFAULT 15,
    source text,
    email_id int8,
    dedup_key varchar,
    updated_at timestamptz DEFAULT now(),
    is_current bool DEFAULT true,
    version int4 DEFAULT 1,
    supersedes_id int8,
    recurrence text
);

ALTER TABLE public.tasks ADD PRIMARY KEY (id);

ALTER TABLE public ADD CONSTRAINT tasks_project_id_fkey FOREIGN KEY (tasks) REFERENCES public(projects);

-- TABLE: public.raw_dumps
CREATE TABLE public.raw_dumps (
    id int8 GENERATED ALWAYS AS IDENTITY,
    content text,
    source text DEFAULT 'telegram'::text,
    is_processed bool DEFAULT false,
    created_at timestamptz DEFAULT now(),
    metadata jsonb,
    status text DEFAULT 'pending'::text,
    embedding vector,
    request_id text,
    direction text DEFAULT 'incoming'::text,
    sender text DEFAULT 'telegram'::text,
    message_type text DEFAULT 'chat'::text,
    dedup_key text
);

ALTER TABLE public.raw_dumps ADD PRIMARY KEY (id);


-- TABLE: public.people
CREATE TABLE public.people (
    id int8 GENERATED ALWAYS AS IDENTITY,
    name text,
    role text,
    strategic_weight int4 DEFAULT 5,
    created_at timestamptz DEFAULT now(),
    source text
);

ALTER TABLE public.people ADD PRIMARY KEY (id);

ALTER TABLE public ADD CONSTRAINT emails_linked_person_id_fkey FOREIGN KEY (emails) REFERENCES public(people);

-- TABLE: public.resources
CREATE TABLE public.resources (
    id int8 GENERATED BY DEFAULT AS IDENTITY,
    url text,
    title text,
    summary text,
    category text,
    project_id int8,
    created_at timestamptz DEFAULT now(),
    strategic_note text,
    cluster_id int8,
    enriched_at timestamptz,
    embedding vector,
    is_current bool DEFAULT true,
    version int4 DEFAULT 1,
    supersedes_id int4
);

ALTER TABLE public.resources ADD PRIMARY KEY (id);

ALTER TABLE public ADD CONSTRAINT resources_cluster_id_fkey FOREIGN KEY (resources) REFERENCES public(clusters);
ALTER TABLE public ADD CONSTRAINT resources_project_id_fkey FOREIGN KEY (resources) REFERENCES public(projects);

-- TABLE: public.clusters
CREATE TABLE public.clusters (
    id int8 GENERATED BY DEFAULT AS IDENTITY,
    title text,
    status text DEFAULT 'active'::text,
    created_at timestamptz DEFAULT now(),
    description text
);

ALTER TABLE public.clusters ADD PRIMARY KEY (id);

ALTER TABLE public ADD CONSTRAINT resources_cluster_id_fkey FOREIGN KEY (resources) REFERENCES public(clusters);

-- TABLE: public.memories
CREATE TABLE public.memories (
    id int8 DEFAULT nextval('memories_id_seq'::regclass),
    content text,
    metadata jsonb,
    embedding vector,
    created_at timestamptz DEFAULT now(),
    memory_type text DEFAULT 'note'::text,
    source text,
    embedding_status text DEFAULT 'success'::text CHECK (embedding_status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text])),
    is_archived bool DEFAULT false,
    archived_at timestamptz,
    archive_reason text,
    importance_score int4 DEFAULT 5 CHECK (importance_score >= 1 AND importance_score <= 10),
    last_accessed_at timestamptz DEFAULT now(),
    supersedes_id uuid,
    pruned bool DEFAULT false,
    pruned_at timestamptz,
    pruned_reason text,
    superseded_by uuid,
    is_current bool DEFAULT true,
    version int4 DEFAULT 1,
    project_id int8
);

ALTER TABLE public.memories ADD PRIMARY KEY (id);

ALTER TABLE public ADD CONSTRAINT memories_project_id_fkey FOREIGN KEY (memories) REFERENCES public(projects);

-- TABLE: public.agent_queue
CREATE TABLE public.agent_queue (
    id int4 DEFAULT nextval('agent_queue_id_seq'::regclass),
    query text,
    status text DEFAULT 'pending'::text,
    priority text DEFAULT 'batch'::text,
    created_at timestamptz DEFAULT now(),
    completed_at timestamptz,
    task text,
    metadata jsonb
);

ALTER TABLE public.agent_queue ADD PRIMARY KEY (id);


-- TABLE: public.graph_nodes
CREATE TABLE public.graph_nodes (
    id uuid DEFAULT gen_random_uuid(),
    label text,
    type text,
    metadata jsonb,
    embedding vector,
    canonical_page_id int4
);

ALTER TABLE public.graph_nodes ADD PRIMARY KEY (id);

ALTER TABLE public ADD CONSTRAINT graph_nodes_canonical_page_id_fkey FOREIGN KEY (graph_nodes) REFERENCES public(canonical_pages);
ALTER TABLE public ADD CONSTRAINT graph_edges_target_node_id_fkey FOREIGN KEY (graph_edges) REFERENCES public(graph_nodes);
ALTER TABLE public ADD CONSTRAINT graph_edges_source_node_id_fkey FOREIGN KEY (graph_edges) REFERENCES public(graph_nodes);

-- TABLE: public.graph_edges
CREATE TABLE public.graph_edges (
    id uuid DEFAULT extensions.uuid_generate_v4(),
    source_node_id uuid,
    target_node_id uuid,
    relationship text,
    weight float8,
    metadata jsonb,
    created_at timestamptz DEFAULT now()
);

ALTER TABLE public.graph_edges ADD PRIMARY KEY (id);

ALTER TABLE public ADD CONSTRAINT graph_edges_source_node_id_fkey FOREIGN KEY (graph_edges) REFERENCES public(graph_nodes);
ALTER TABLE public ADD CONSTRAINT graph_edges_target_node_id_fkey FOREIGN KEY (graph_edges) REFERENCES public(graph_nodes);

-- TABLE: public.canonical_pages
CREATE TABLE public.canonical_pages (
    id int8 GENERATED BY DEFAULT AS IDENTITY,
    title text,
    content text,
    category text,
    entity_id uuid,
    embedding vector,
    updated_at timestamptz DEFAULT now(),
    project_id int4,
    source_count int4 DEFAULT 0,
    last_synth_at timestamptz,
    is_sparse bool DEFAULT false,
    is_archived bool DEFAULT false,
    archived_at timestamptz,
    archive_reason text,
    is_current bool DEFAULT true,
    version int4 DEFAULT 1,
    supersedes_id int8
);

ALTER TABLE public.canonical_pages ADD PRIMARY KEY (id);

ALTER TABLE public ADD CONSTRAINT canonical_pages_project_id_fkey FOREIGN KEY (canonical_pages) REFERENCES public(projects);
ALTER TABLE public ADD CONSTRAINT graph_nodes_canonical_page_id_fkey FOREIGN KEY (graph_nodes) REFERENCES public(canonical_pages);

-- TABLE: public.pulse_runs
CREATE TABLE public.pulse_runs (
    id int8 GENERATED ALWAYS AS IDENTITY,
    status text DEFAULT 'running'::text,
    started_at timestamptz DEFAULT now(),
    completed_at timestamptz,
    failed_at timestamptz,
    error_message text,
    dumps_processed int4,
    tasks_created int4,
    pulse_type text,
    trigger text,
    metadata jsonb DEFAULT '{}'::jsonb
);

ALTER TABLE public.pulse_runs ADD PRIMARY KEY (id);


-- TABLE: public.emails
CREATE TABLE public.emails (
    id int4 DEFAULT nextval('emails_id_seq'::regclass),
    message_id text,
    thread_id text,
    source text,
    sender text DEFAULT 'unknown'::text,
    sender_email text DEFAULT 'unknown'::text,
    subject text,
    body_summary text,
    received_at timestamptz,
    classification text,
    status text DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'processing'::text, 'processed'::text, 'needs_reply'::text, 'snoozed'::text, 'error'::text, 'ignored'::text])),
    linked_person_id int4,
    linked_project_id int4,
    created_at timestamptz DEFAULT now(),
    gmail_labels _text DEFAULT '{}'::text[],
    embedding vector,
    body_raw text
);

ALTER TABLE public.emails ADD PRIMARY KEY (id);

ALTER TABLE public ADD CONSTRAINT email_pending_tasks_email_id_fkey FOREIGN KEY (email_pending_tasks) REFERENCES public(emails);
ALTER TABLE public ADD CONSTRAINT emails_linked_person_id_fkey FOREIGN KEY (emails) REFERENCES public(people);
ALTER TABLE public ADD CONSTRAINT emails_linked_project_id_fkey FOREIGN KEY (emails) REFERENCES public(projects);
ALTER TABLE public ADD CONSTRAINT email_drafts_email_id_fkey FOREIGN KEY (email_drafts) REFERENCES public(emails);

-- TABLE: public.email_drafts
CREATE TABLE public.email_drafts (
    id int4 DEFAULT nextval('email_drafts_id_seq'::regclass),
    email_id int4,
    draft_body text,
    status text DEFAULT 'pending'::text,
    created_at timestamptz DEFAULT now(),
    reviewed_at timestamptz
);

ALTER TABLE public.email_drafts ADD PRIMARY KEY (id);

ALTER TABLE public ADD CONSTRAINT email_drafts_email_id_fkey FOREIGN KEY (email_drafts) REFERENCES public(emails);

-- TABLE: public.email_pending_tasks
CREATE TABLE public.email_pending_tasks (
    id int4 DEFAULT nextval('email_pending_tasks_id_seq'::regclass),
    email_id int4,
    suggested_title text,
    suggested_project text,
    shown_in_brief bool DEFAULT false,
    danny_decision text,
    created_at timestamptz DEFAULT now(),
    is_human_sender bool DEFAULT false,
    suggested_project_id int8,
    project_confidence float8 CHECK (project_confidence >= 0::double precision AND project_confidence <= 1::double precision),
    project_mapping_reason text,
    possible_duplicate bool,
    duplicate_of_title text
);

ALTER TABLE public.email_pending_tasks ADD PRIMARY KEY (id);

ALTER TABLE public ADD CONSTRAINT email_pending_tasks_email_id_fkey FOREIGN KEY (email_pending_tasks) REFERENCES public(emails);
ALTER TABLE public ADD CONSTRAINT email_pending_tasks_suggested_project_id_fkey FOREIGN KEY (email_pending_tasks) REFERENCES public(projects);

-- TABLE: public.failed_queue
CREATE TABLE public.failed_queue (
    id int8 DEFAULT nextval('failed_queue_id_seq'::regclass),
    source_table text,
    source_id text,
    operation text,
    error_message text,
    retry_count int4 DEFAULT 0,
    last_retry_at timestamptz,
    created_at timestamptz DEFAULT now(),
    metadata jsonb DEFAULT '{}'::jsonb
);

ALTER TABLE public.failed_queue ADD PRIMARY KEY (id);


-- TABLE: public.audit_logs
CREATE TABLE public.audit_logs (
    id int8 DEFAULT nextval('audit_logs_id_seq'::regclass),
    service text,
    level text,
    message text,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamptz DEFAULT now()
);

ALTER TABLE public.audit_logs ADD PRIMARY KEY (id);


-- TABLE: public.model_registry
CREATE TABLE public.model_registry (
    id uuid DEFAULT gen_random_uuid(),
    model_name text,
    provider text,
    version text,
    input_tokens int4,
    output_tokens int4,
    latency_ms int4,
    success bool DEFAULT true,
    error_message text,
    created_at timestamptz DEFAULT now(),
    metadata jsonb DEFAULT '{}'::jsonb
);

ALTER TABLE public.model_registry ADD PRIMARY KEY (id);


-- TABLE: public.processed_updates
CREATE TABLE public.processed_updates (
    id uuid DEFAULT gen_random_uuid(),
    update_id int8,
    chat_id int8,
    processed_at timestamptz DEFAULT now(),
    request_id text,
    metadata jsonb DEFAULT '{}'::jsonb
);

ALTER TABLE public.processed_updates ADD PRIMARY KEY (id);


-- TABLE: public.conversations
CREATE TABLE public.conversations (
    id int8 GENERATED ALWAYS AS IDENTITY,
    chat_id int8,
    session_id uuid,
    role text CHECK (role = ANY (ARRAY['user'::text, 'bot'::text])),
    intent text,
    content text,
    token_count int4 DEFAULT 0,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamptz DEFAULT now()
);

ALTER TABLE public.conversations ADD PRIMARY KEY (id);


-- TABLE: public.call_recordings
CREATE TABLE public.call_recordings (
    id int8 DEFAULT nextval('call_recordings_id_seq'::regclass),
    drive_file_id text,
    drive_file_name text,
    mime_type text,
    file_size_bytes int8,
    duration_seconds int4,
    transcript text,
    extraction jsonb,
    status text DEFAULT 'pending'::text,
    metadata jsonb,
    created_at timestamptz DEFAULT now(),
    processed_at timestamptz,
    error_message text
);

ALTER TABLE public.call_recordings ADD PRIMARY KEY (id);

ALTER TABLE public ADD CONSTRAINT call_pending_items_recording_id_fkey FOREIGN KEY (call_pending_items) REFERENCES public(call_recordings);

-- TABLE: public.call_pending_items
CREATE TABLE public.call_pending_items (
    id int8 DEFAULT nextval('call_pending_items_id_seq'::regclass),
    recording_id int8,
    suggested_title text,
    suggested_project text,
    action_type text,
    summary text,
    people_mentioned jsonb,
    danny_decision text,
    shown_in_brief bool DEFAULT false,
    possible_duplicate bool DEFAULT false,
    created_at timestamptz DEFAULT now(),
    decided_at timestamptz
);

ALTER TABLE public.call_pending_items ADD PRIMARY KEY (id);

ALTER TABLE public ADD CONSTRAINT call_pending_items_recording_id_fkey FOREIGN KEY (call_pending_items) REFERENCES public(call_recordings);

-- TABLE: public.whatsapp_messages
CREATE TABLE public.whatsapp_messages (
    id int8 GENERATED BY DEFAULT AS IDENTITY,
    sender_name text,
    sender_phone text,
    message_text text,
    classification text,
    summary text,
    suggested_title text,
    suggested_project text,
    linked_person_name text,
    has_memory_value bool DEFAULT false,
    shown_in_brief bool DEFAULT false,
    danny_decision text,
    decided_at timestamptz,
    received_at timestamptz DEFAULT now(),
    created_at timestamptz DEFAULT now(),
    embedding vector
);

ALTER TABLE public.whatsapp_messages ADD PRIMARY KEY (id);


